namespace Loom.Telemetry;

/// <summary>
/// The type of metric being recorded.
/// </summary>
public enum MetricType : byte
{
    /// <summary>Monotonically increasing counter (e.g., request count, errors)</summary>
    Counter = 0,

    /// <summary>Point-in-time value that can go up or down (e.g., CPU%, memory usage)</summary>
    Gauge = 1,

    /// <summary>Distribution of values (e.g., request latency, response sizes)</summary>
    Histogram = 2,

    /// <summary>Method execution timing (generated by [LoomProfile])</summary>
    MethodExecution = 3
}
