using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Loom.Telemetry.Generators
{
    [Generator]
    public sealed class LoomProfileGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Emit attributes
            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("LoomAttributes.g.cs", AttributesSource);
            });

            // Find profiled methods
            var profiledMethods = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Loom.Telemetry.LoomProfileAttribute",
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, _) => GetMethodInfo(ctx))
                .Where(static m => m != null)
                .Collect();

            // Find tracked properties
            var trackedProperties = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Loom.Telemetry.LoomTrackAttribute",
                    predicate: static (node, _) => node is PropertyDeclarationSyntax,
                    transform: static (ctx, _) => GetPropertyInfo(ctx))
                .Where(static p => p != null)
                .Collect();

            // Generate profiled wrappers
            context.RegisterSourceOutput(profiledMethods, static (spc, methods) =>
            {
                foreach (var group in methods.GroupBy(m => m!.ContainingType))
                {
                    var source = GenerateProfiledWrappers(group.Key, group.ToList()!);
                    var fileName = SanitizeFileName($"{group.Key}.LoomProfile.g.cs");
                    spc.AddSource(fileName, source);
                }
            });

            // Generate tracked property implementations
            context.RegisterSourceOutput(trackedProperties, static (spc, properties) =>
            {
                foreach (var group in properties.GroupBy(p => p!.ContainingType))
                {
                    var source = GenerateTrackedProperties(group.Key, group.ToList()!);
                    var fileName = SanitizeFileName($"{group.Key}.LoomTrack.g.cs");
                    spc.AddSource(fileName, source);
                }
            });
        }

        private static MethodInfo? GetMethodInfo(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetNode is not MethodDeclarationSyntax method)
                return null;

            var symbol = context.TargetSymbol as IMethodSymbol;
            if (symbol == null)
                return null;

            var attribute = context.Attributes.FirstOrDefault();
            var explicitName = attribute?.NamedArguments
                .FirstOrDefault(kv => kv.Key == "Name")
                .Value.Value as string;

            return new MethodInfo
            {
                Method = method,
                Symbol = symbol,
                ContainingType = symbol.ContainingType.ToDisplayString(),
                MetricName = explicitName ?? $"{symbol.ContainingType.Name}.{symbol.Name}",
                IsAsync = symbol.IsAsync,
                ReturnsVoid = symbol.ReturnsVoid,
                ReturnType = symbol.ReturnType.ToDisplayString(),
                IsStatic = symbol.IsStatic
            };
        }

        private static string GenerateProfiledWrappers(string containingType, List<MethodInfo> methods)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Diagnostics;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Loom.Telemetry;");
            sb.AppendLine();

            var namespaceName = GetNamespace(containingType);
            var className = GetClassName(containingType);

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            // Generate extension class for instance methods or static class for static methods
            sb.AppendLine($"    public static class {SanitizeIdentifier(className)}_LoomProfileExtensions");
            sb.AppendLine("    {");

            foreach (var method in methods)
            {
                GenerateProfiledWrapper(sb, method);
            }

            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void GenerateProfiledWrapper(StringBuilder sb, MethodInfo methodInfo)
        {
            var symbol = methodInfo.Symbol;
            var parameters = string.Join(", ", symbol.Parameters.Select(p =>
                $"{p.Type.ToDisplayString()} {p.Name}"));

            var arguments = string.Join(", ", symbol.Parameters.Select(p => p.Name));

            var thisParam = methodInfo.IsStatic ? "" : $"this {methodInfo.ContainingType} instance";
            var fullParams = string.IsNullOrEmpty(thisParam) ? parameters :
                string.IsNullOrEmpty(parameters) ? thisParam : $"{thisParam}, {parameters}";

            var methodCall = methodInfo.IsStatic
                ? $"{methodInfo.ContainingType}.{symbol.Name}({arguments})"
                : $"instance.{symbol.Name}({arguments})";

            var wrapperName = $"{symbol.Name}_Profiled";

            sb.AppendLine($"        /// <summary>Profiled wrapper for {symbol.Name}</summary>");
            sb.AppendLine($"        [MethodImpl(MethodImplOptions.AggressiveInlining)]");

            if (methodInfo.IsAsync)
            {
                // Async wrapper
                sb.AppendLine($"        public static async {methodInfo.ReturnType} {wrapperName}({fullParams})");
                sb.AppendLine("        {");
                sb.AppendLine("            var __startTicks = Stopwatch.GetTimestamp();");
                sb.AppendLine("            try");
                sb.AppendLine("            {");

                if (methodInfo.ReturnType == "System.Threading.Tasks.Task")
                {
                    sb.AppendLine($"                await {methodCall}.ConfigureAwait(false);");
                    sb.AppendLine("                var __elapsed = Stopwatch.GetElapsedTime(__startTicks);");
                    sb.AppendLine($"                LoomRuntime.RecordMethodExecution(\"{methodInfo.MetricName}\", __elapsed, null);");
                }
                else
                {
                    sb.AppendLine($"                var __result = await {methodCall}.ConfigureAwait(false);");
                    sb.AppendLine("                var __elapsed = Stopwatch.GetElapsedTime(__startTicks);");
                    sb.AppendLine($"                LoomRuntime.RecordMethodExecution(\"{methodInfo.MetricName}\", __elapsed, null);");
                    sb.AppendLine("                return __result;");
                }

                sb.AppendLine("            }");
                sb.AppendLine("            catch (Exception __ex)");
                sb.AppendLine("            {");
                sb.AppendLine("                var __elapsed = Stopwatch.GetElapsedTime(__startTicks);");
                sb.AppendLine($"                LoomRuntime.RecordMethodExecution(\"{methodInfo.MetricName}\", __elapsed, __ex);");
                sb.AppendLine("                throw;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            else
            {
                // Sync wrapper
                sb.AppendLine($"        public static {methodInfo.ReturnType} {wrapperName}({fullParams})");
                sb.AppendLine("        {");
                sb.AppendLine("            var __startTicks = Stopwatch.GetTimestamp();");
                sb.AppendLine("            try");
                sb.AppendLine("            {");

                if (methodInfo.ReturnsVoid)
                {
                    sb.AppendLine($"                {methodCall};");
                    sb.AppendLine("                var __elapsed = Stopwatch.GetElapsedTime(__startTicks);");
                    sb.AppendLine($"                LoomRuntime.RecordMethodExecution(\"{methodInfo.MetricName}\", __elapsed, null);");
                }
                else
                {
                    sb.AppendLine($"                var __result = {methodCall};");
                    sb.AppendLine("                var __elapsed = Stopwatch.GetElapsedTime(__startTicks);");
                    sb.AppendLine($"                LoomRuntime.RecordMethodExecution(\"{methodInfo.MetricName}\", __elapsed, null);");
                    sb.AppendLine("                return __result;");
                }

                sb.AppendLine("            }");
                sb.AppendLine("            catch (Exception __ex)");
                sb.AppendLine("            {");
                sb.AppendLine("                var __elapsed = Stopwatch.GetElapsedTime(__startTicks);");
                sb.AppendLine($"                LoomRuntime.RecordMethodExecution(\"{methodInfo.MetricName}\", __elapsed, __ex);");
                sb.AppendLine("                throw;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            sb.AppendLine();
        }

        private static PropertyInfo? GetPropertyInfo(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetNode is not PropertyDeclarationSyntax property)
                return null;

            var symbol = context.TargetSymbol as IPropertySymbol;
            if (symbol == null)
                return null;

            // Only support auto-properties (no custom getter/setter)
            if (property.AccessorList == null)
                return null;

            var attribute = context.Attributes.FirstOrDefault();
            var explicitName = attribute?.NamedArguments
                .FirstOrDefault(kv => kv.Key == "Name")
                .Value.Value as string;

            return new PropertyInfo
            {
                Property = property,
                Symbol = symbol,
                ContainingType = symbol.ContainingType.ToDisplayString(),
                MetricName = explicitName ?? $"{symbol.ContainingType.Name}.{symbol.Name}",
                PropertyType = symbol.Type.ToDisplayString(),
                PropertyName = symbol.Name
            };
        }

        private static string GenerateTrackedProperties(string containingType, List<PropertyInfo> properties)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Loom.Telemetry;");
            sb.AppendLine();

            var namespaceName = GetNamespace(containingType);
            var className = GetClassName(containingType);

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    partial class {className}");
            sb.AppendLine("    {");

            foreach (var prop in properties)
            {
                GenerateTrackedProperty(sb, prop);
            }

            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void GenerateTrackedProperty(StringBuilder sb, PropertyInfo prop)
        {
            var backingField = $"__loom_tracked_{prop.PropertyName}";

            // Generate backing field
            sb.AppendLine($"        private {prop.PropertyType} {backingField};");
            sb.AppendLine();

            // Generate property with tracking
            sb.AppendLine($"        /// <summary>Tracked property - records changes to LoomMetrics</summary>");
            sb.AppendLine($"        public {prop.PropertyType} {prop.PropertyName}_Tracked");
            sb.AppendLine("        {");
            sb.AppendLine($"            get => {backingField};");
            sb.AppendLine("            set");
            sb.AppendLine("            {");
            sb.AppendLine($"                {backingField} = value;");
            sb.AppendLine($"                LoomRuntime.RecordPropertyChange(\"{prop.MetricName}\", value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static string GetNamespace(string fullTypeName)
        {
            var lastDot = fullTypeName.LastIndexOf('.');
            return lastDot > 0 ? fullTypeName.Substring(0, lastDot) : string.Empty;
        }

        private static string GetClassName(string fullTypeName)
        {
            var lastDot = fullTypeName.LastIndexOf('.');
            return lastDot > 0 ? fullTypeName.Substring(lastDot + 1) : fullTypeName;
        }

        private static string SanitizeFileName(string name)
        {
            return name.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(':', '_');
        }

        private static string SanitizeIdentifier(string name)
        {
            return name.Replace('.', '_').Replace('<', '_').Replace('>', '_');
        }

        private const string AttributesSource = @"// <auto-generated/>
#nullable enable
using System;

namespace Loom.Telemetry
{
    /// <summary>
    /// Marks a method for automatic profiling instrumentation.
    /// The generator will create a *_Profiled() wrapper method with timing.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class LoomProfileAttribute : Attribute
    {
        /// <summary>Optional explicit metric name. Defaults to ClassName.MethodName</summary>
        public string? Name { get; init; }
    }

    /// <summary>
    /// Marks a property for value-change tracking.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class LoomTrackAttribute : Attribute
    {
        /// <summary>Optional explicit metric name. Defaults to ClassName.PropertyName</summary>
        public string? Name { get; init; }
    }
}";

        private sealed class MethodInfo
        {
            public MethodDeclarationSyntax Method { get; init; } = null!;
            public IMethodSymbol Symbol { get; init; } = null!;
            public string ContainingType { get; init; } = null!;
            public string MetricName { get; init; } = null!;
            public bool IsAsync { get; init; }
            public bool ReturnsVoid { get; init; }
            public string ReturnType { get; init; } = null!;
            public bool IsStatic { get; init; }
        }

        private sealed class PropertyInfo
        {
            public PropertyDeclarationSyntax Property { get; init; } = null!;
            public IPropertySymbol Symbol { get; init; } = null!;
            public string ContainingType { get; init; } = null!;
            public string MetricName { get; init; } = null!;
            public string PropertyType { get; init; } = null!;
            public string PropertyName { get; init; } = null!;
        }
    }
}
